### ISSUE TITLE
SASL_SSL / SCRAM support

### ISSUE THREAD

**Issue by krisek** [aiven/karapace#153]
Hi, 

as far as I understand SASL_SSL is not supported (and consequently SCRAM-SHA-512 is not supported too) any plans for this or eventually a hint where should I start to hack?

**Comment by krisek** [comment]
Finally I managed to inject the functionality by

- using python-kafka from https://github.com/aiven/kafka-python:aiven-20212201:1b95333: appearantly this commit contains the _send_request_to_least_loaded_node function which is referred in kafka_rest_apis/admin.py
- removing the self.kafka_client parameters from the _init function in kafka_rest_apis/__init__.py and somewhere else

Is this OK? Can you include this in upstream if I raise a PR? Maybe the self.kafka_client parameters have something to do with the different python-kafka versions.

**Comment by hnousiainen** [comment]
Hello @krisek,

We would most certainly welcome PRs on that topic. Our own operation uses SSL authentication, so we didn't yet have our own plans for extending support to SASL_SSL.

Since Karapace uses kafka-python, supporting SASL should be a matter of propagating the suitable config to the consumer/producer instances (grep for e.g. bootstrap_servers). We have some SASL examples for kafka-python listed in this help article: https://help.aiven.io/en/articles/489572-getting-started-with-aiven-kafka

**Comment by krisek** [comment]
Hi Hekki @hnousiainen, 

actually the functionality is implemented, what about the dependency on _send_request_to_least_loaded_node from aiven-kafka and the self.kafka_client params in the init.py?

Should I raise the PR with or without them?

**Comment by hackaugusto** [comment]
Hey @krisek , `_send_request_to_least_loaded_node` is an important bugfix, It is currently waiting on upstream for code review. [bugfix: fix infinite loop on KafkaAdminClient #2194](https://github.com/dpkp/kafka-python/pull/2194). Until the changes are merged [I'd recommend using our fork](https://github.com/aiven/karapace/blob/27c84fa7ebbd85228010d3a7e8a223e57b7ab96c/requirements-dev.txt#L13-L15)

For `SASL_SSL` support, it only needs validation of the configuration and then pass it to the class constructors in a few places:
 
- [KafkaProducer](https://github.com/aiven/karapace/blob/27c84fa7ebbd85228010d3a7e8a223e57b7ab96c/karapace/karapace.py#L47-L58)
- [KafkaConsumer](https://github.com/aiven/karapace/blob/27c84fa7ebbd85228010d3a7e8a223e57b7ab96c/karapace/schema_reader.py#L118-L133) , and [for the rest api](https://github.com/aiven/karapace/blob/27c84fa7ebbd85228010d3a7e8a223e57b7ab96c/karapace/kafka_rest_apis/consumer_manager.py#L176-L190)
- [KafkaAdminClient](https://github.com/aiven/karapace/blob/27c84fa7ebbd85228010d3a7e8a223e57b7ab96c/karapace/schema_reader.py#L137-L145)
- [AIOKafkaProducer](https://github.com/aiven/karapace/blob/27c84fa7ebbd85228010d3a7e8a223e57b7ab96c/karapace/kafka_rest_apis/__init__.py#L179-L189)

I hope this helps :)
