### ISSUE TITLE
Trying to install, getting Exception: version not available from git or from file '/root/karapace-master/karapace/version.py'

### ISSUE THREAD

**Issue by michTalebzadeh** [aiven/karapace#176]
Hi,

I have downloaded the zip file from this GitHub and following instructions to install. I need to create a schema registry for my Kafka topic.

```
(airflow_virtualenv) [root@rhes75 karapace-master]# python3 setup.py bdist_egg
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    version_for_setup_py = version.get_project_version("karapace/version.py")
  File "/root/karapace-master/version.py", line 43, in get_project_version
    raise Exception("version not available from git or from file {!r}".format(version_file))
Exception: version not available from git or from file '/root/karapace-master/karapace/version.py'
```

Kindly advise a workaround.

Thanks,

Mich

**Comment by lornajane** [comment]
I think there's already discussion of this in a similar issue: #157

**Comment by hackaugusto** [comment]
Hi @michTalebzadeh , thank you for the report. The workaround is to install from a `git clone` instead of the zip file.

**Comment by hackaugusto** [comment]
As an alternative, you can [also use docker](https://github.com/aiven/karapace#docker-setup-for-development). I'm going to close the issue for now, if you have more questions fell free to open a new issue :)
