### ISSUE TITLE
How to use Karapace with JSON

### ISSUE THREAD

**Issue by timsuchanek** [aiven/karapace#207]
Hi, right now when following the steps from https://github.com/aiven/karapace, we serialize in avro format. Is it possible to just serialize in JSON or even skip the schema?
We're using Clickhouse DB hosted in Altinity Cloud and setting up the schema registry URL turns out tricky. Thanks!

**Comment by hackaugusto** [comment]
Hi @timsuchanek .

> Is it possible to just serialize in JSON or even skip the schema?

The Schema REST APIs are doing only JSON. For example:

```sh
$ curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schema": "{\"type\": \"record\", \"name\": \"Obj\", \"fields\":[{\"name\": \"age\", \"type\": \"int\"}]}"}' \
  http://localhost:8081/subjects/test-key/versions
```
The data in the POST is a JSON document. The document has `schema` key:
```json
{
  "schema": "{\"type\": \"record\", \"name\": \"Obj\", \"fields\":[{\"name\": \"age\", \"type\": \"int\"}]}"
}
```
The value of that key is a JSON document encoded in a string. After parsing it looks like this:
```json
{
  "type": "record",
  "name": "Obj",
  "fields": [
    {
      "name": "age",
      "type": "int"
    }
  ]
}
```
That [JSON document describes the AVRO format](https://avro.apache.org/docs/current/spec.html#schemas).

If you don't want to use AVRO in your application, the registry also support JSON schemas. I hope this helps.

**Comment by hackaugusto** [comment]
It seems the question was answered, closing the issue. If you have additional questions feel free to re-open or create a new issue :)
