### ISSUE TITLE
Integration testing against Schema Registry

### ISSUE THREAD

**Issue by juha-aiven** [aiven/karapace#244]
# What is currently missing?

Currently the integration tests are run against Karapace. In order to validate compatibility with Schema Registry and Kafka REST, the tests can be manually run against those. However, this is fully manual step not e.g. enforced in the CI pipeline

# How could this be improved?

We could e.g. improve the CI pipeline to run the tests against Schema Registry and Karapace.

**Comment by hackaugusto** [comment]
won't do: possible issues with license of schema registry
