### ISSUE TITLE
Proper releases

### ISSUE THREAD

**Issue by juha-aiven** [aiven/karapace#245]
# What is currently missing?

- [x] tagged releases
- [x] docker image realeases
- [ ] PyPI package releases

**Comment by jlprat** [comment]
We should also define the maintenance period for the releases. Or at least a strategy that would define the EOL for each version.

**Comment by jlprat** [comment]
I would propose the following:
- Karapace uses semantic versioning with major.minor.patch schema
- Karapace two latest minor versions are always maintained with bug fixes and security upgrades
- GitHub Workflow action is used to release Karapace versions
- Milestones are created for each release
- Closed issues or merged PRs without issues are assigned to the corresponding milestone
- Release notes are pseudo automatic: Script gathers all titles of Issues (and PRs without issues) that were closed in a milestone. Developer intervention might be used to clean up or polish the text
- Releases are announced in Aiven's twitter and developer portal, as well as in GitHub's release section

**Comment by lornajane** [comment]
To me this seems like a lot to introduce all in one go. I propose that we start start by putting in a process for publishing releases and release notes, these would be huge wins. We can build on that foundation in future and add other items from the list.

**Comment by jlprat** [comment]
I agree with you, maybe I should have said that this was my wish-list for the release process instead of  saying that this was my proposal.

**Comment by aiven-anton** [comment]
Do we really want to have PyPI releases? Karapace is not a library (it's an application), and keeping that distinction clear is important to not introduce dependents of implementation details and internals. IMO it's completely fine to only provide the two current installation options:

- Manually manage system dependencies + install from source.
- Docker container image.

So, is practice of using tags + building docker images from releases enough to close this issue?

**Comment by aiven-anton** [comment]
I opened #587, to formalize my opinion that Karapace is not an application, explicitly specify that we use semantic versioning, as well as which entry-points are considered "public", i.e. to fall under the semantic versioning policy.

**Comment by tvainika** [comment]
I agree that we do not want PyPI package releases, because Karapace is an application. Therefore closing now as all wanted sub-tasks are done.
