### ISSUE TITLE
Running with docker compose fails

### ISSUE THREAD

**Issue by ElmShahar** [aiven/karapace#252]
# What happened?
Tried to run locally and on a server using the docker-compose file. 
`docker-compose -f ./container/docker-compose.yml up -d`

Tried to access the front end and got an empty json response
{}

# What did you expect to happen?
Have a working installation of karapace 

# What else do we need to know?
docker-compose log - 
[output.log](https://github.com/aiven/karapace/files/6668193/output.log)

Include your platform, version, and any other information that seems relevant.
Tried on local mac OSX ver 11.2.3, docker version 20.10.6 and on Amazon linux 2 server, docker version 19.03.13-ce

**Comment by hackaugusto** [comment]
```
Tried to access the front end and got an empty json response
{}
```
Hey, Karapace does not have a front end, as in a HTML page, only REST APIs. From your report it seems that Karapce is up and running, you can explore the other APIs with help of the [quickstart](https://github.com/aiven/karapace#quickstart)

I'm closing the issue, but if you have more questions feel free to open reopen it :)
