### ISSUE TITLE
What's the correct Content-Type header for JSON schema?

### ISSUE THREAD

**Issue by adriank-convoy** [aiven/karapace#253]
# What can we help you with?

I'm trying to POST a new JSON schema, but I'm getting back a 415 error code with the message "HTTP 415 Unsupported Media Type". I'm using the headers I found at https://github.com/aiven/karapace/blob/6c7ed9c811e47923d83ab2fc649537b59ce0a16e/tests/utils.py#L89-L92 so

```
--header 'Content-Type: application/vnd.kafka.jsonschema.v2+json' \
--header 'Accept: application/vnd.kafka.jsonschema.v2+json, application/vnd.kafka.v2+json, application/json, */*' 
```
but no luck. It actually seems like `application/vnd.schemaregistry.v1+json` and `application/json` are the only accepted content type, but both assume an Avro schema.

# Where would you expect to find this information?

It would be great to have example `curl` requests in the Quickstart section of the repo's README for all supported schema types

**Comment by adriank-convoy** [comment]
As a follow up, I figured this out after finally finding an example in an issue in the `confluentinc/schema-registry` repo. The `Content-Type` header should be `application/vnd.schemaregistry.v1+json` regardless of the schema type, and the body of the request should contain `"schemaType": "JSON"` (or Avro, or any other type). Here's an example curl request:

```
curl --request POST 'http://localhost:8081/subjects/MyTestEvent/versions' \
--header 'Content-Type: application/vnd.schemaregistry.v1+json' \
--header 'Accept: application/json' \
--data-raw '{"schemaType": "JSON", "schema": "{\"$schema\":\"http://json-schema.org/draft-07/schema\",\"$id\":\"http://example.com/example.json\",\"type\":\"object\",\"required\":[\"checked\",\"dimensions\",\"id\",\"name\",\"price\",\"tags\"],\"properties\":{\"checked\":{\"$id\":\"#/properties/checked\",\"type\":\"boolean\"},\"dimensions\":{\"$id\":\"#/properties/dimensions\",\"type\":\"object\",\"required\":[\"width\",\"height\"],\"properties\":{\"width\":{\"$id\":\"#/properties/dimensions/properties/width\",\"type\":\"integer\"},\"height\":{\"$id\":\"#/properties/dimensions/properties/height\",\"type\":\"integer\"}},\"additionalProperties\":true},\"id\":{\"$id\":\"#/properties/id\",\"type\":\"integer\"},\"name\":{\"$id\":\"#/properties/name\",\"type\":\"string\"},\"price\":{\"$id\":\"#/properties/price\",\"type\":\"number\"},\"tags\":{\"$id\":\"#/properties/tags\",\"type\":\"array\",\"additionalItems\":true,\"items\":{\"$id\":\"#/properties/tags/items\",\"anyOf\":[{\"$id\":\"#/properties/tags/items/anyOf/0\",\"type\":\"string\"}]}}},\"additionalProperties\":true}"}'
```

**Comment by lornajane** [comment]
Thanks for dropping by with the question and especially with the answer! I'll leave this issue open until we get the information included in documentation.
