### ISSUE TITLE
Karapace with kind cluster

### ISSUE THREAD

**Issue by Rishikeshpal** [aiven/karapace#256]
Installed karapace-registry on kind cluster through helm -charts(own custom created), installation went fine. Deployment and pods created. 
Pod is backing-off restart.

When i try to see the  container logs , it shows nothing. 

Events:
  Type     Reason   Age                   From     Message
  ----     ------   ----                  ----     -------
  Warning  BackOff  13m (x1435 over 18h)  kubelet  Back-off restarting failed container
  Normal   Pulled   3m16s (x70 over 18h)  kubelet  Container image "aivenoy/karapace:latest" already present on machine

Any suggestions?

**Comment by tvainika** [comment]
Would you mind to share those Helm charts for public usage? In any case the container image of Karapace you've running needs some environment variables to run correctly. The documentation is still work in progress, but docker-compose files under https://github.com/aiven/karapace/tree/master/container can be useful for comparison. Could it be that there are some of those environment variables missing? Of course logging should be improvement to clarify the reason for error. If you're able to share or debug what is missing, it would be faster to improve error logging.

**Comment by Rishikeshpal** [comment]
Sure, i am going to clone and upload the helm charts for public. Also i have carefully looked at the environment variables set for both karapace-registry and karapace-rest and it is set properly, which you would be able to see in the helm chart shortly. I am still tryiing to debug and if i have any luck i shall post it.

**Comment by Rishikeshpal** [comment]
PR created. 
https://github.com/aiven/karapace/pull/257

**Comment by Rishikeshpal** [comment]
@tvainika i have the PR for review ready. It did work on my kind cluster with kafka autheticated.Kindly review.

**Comment by tvainika** [comment]
> It did work on my kind cluster with kafka autheticated.

Do I understand you correctly here that with changes in Helm charts you were able to get Karapace running in your cluster? Does it mean this original issue was fixed by configuration changes? If so, what part of configuration caused original behavior, and can we modify container packaging somehow to make diagnosing such mismatches easier?

**Comment by Rishikeshpal** [comment]
Original issue was that i was missing the commands for the containers to run. Pods came up perfectly once the command args were included in the containers.

**Comment by raminqaf** [comment]
@tvainika It hasn't done much on the PR of this issue for a while. I would like to make a PR and add the Helm charts for Karapace. Would that be okay?

**Comment by Rishikeshpal** [comment]
Helm-charts are part of my PR already, i am going to make a few changes again and then resubmit it.

**Comment by raminqaf** [comment]
@Rishikeshpal Thanks! They need some updates and can be simplified! :rocket:

**Comment by jjaakola-aiven** [comment]
Closing this, inactive.
