### ISSUE TITLE
Use the same protocol when creating a new consumer

### ISSUE THREAD

**Issue by hackaugusto** [aiven/karapace#260]
# What happened?

Created a new consumer with:

```shell
curl --request POST --header 'Content-Type: application/json' --data '{"name":"test","format":"json"}' 'https://<host>:<port>/consumers/test-consumer' 
```

The result was:

```json
{"base_uri":"http://<host>:<port>/consumers/test-consumer/instances/test","instance_id":"test"} 
```

# What did you expect to happen?

The protocol should have stayed `https`

**Comment by tvainika** [comment]
Addition of `advertised_port` and `advertised_protocol` in #400 fixed this as now returned protocol is the configured public address.
