### ISSUE TITLE
Flaky behaviour of GET /topics/<topic-name>/partitions/<partition-id>/offsets

### ISSUE THREAD

**Issue by YuWang24** [aiven/karapace#261]
# What happened?
I tried to run this request: GET /topics/topic-name/partitions/partition-id/offsets. I found some flaky behaviours, sometimes I got the response like below:
`{"beginning_offset":-1,"end_offset":6}`

But sometimes I got a 500 Internal server error:
`{"error_code":500,"message":"Internal server error"}`

# What did you expect to happen?
Response shouldn't be flaky, 500 Internal server error shouldn't be raised. 

# What else do we need to know?

Include your platform, version, and any other information that seems relevant.
Karapace is running on my local machine connecting to my remote Kafka cluster.

**Comment by hackaugusto** [comment]
@YuWang24 could you provide a MRE and the karapace logs? Thanks

**Comment by YuWang24** [comment]
It seems that I cannot reproduce the error at the moment, but I am sure that I got the 500 error several times when I made the GET /topics/topic-name/partitions/partition-id/offsets request.

**Comment by hackaugusto** [comment]
@YuWang24 could you share a bit more details about your setup? Your platform, how are you running Kafka and ZK, the version of Karapace and roughly what was being executed at the time you experience the failure?

**Comment by YuWang24** [comment]
I was using Kafka 2.6.1, Zookeeper 3.5.8, running Karapace 2.0.1 on my Mac laptop using python, connecting my remote Kafka cluster running on a managed platform. I created a topic, then I ran GET /topics/topic-name/partitions/partition-id/offsets, I got the 500 error a few times.
