### ISSUE TITLE
Missing HTTP Basic Authentication for REST Proxy

### ISSUE THREAD

**Issue by YuWang24** [aiven/karapace#262]
# What is currently missing?

As documented in https://docs.confluent.io/platform/current/kafka-rest/production-deployment/rest-proxy/security.html, Confluent supports HTTP Basic Authentication for communication between a client and REST Proxy. However, I cannot find anything related to that being mentioned in Readme or this repo. I am wondering is there a plan to add this kind of authentication for communication between a client and REST Proxy. Is this feature in your roadmap? 
 

# How could this be improved?
Add this feature to enable Basic Authentication for communication between a client and REST Proxy. 

# Is this a feature you would work on yourself?
No.

**Comment by hackaugusto** [comment]
>  I am wondering is there a plan to add this kind of authentication for communication between a client and REST Proxy.

At the moment this is not implemented, for the time a solution is to use a reverse proxy with basic auth support

**Comment by YuWang24** [comment]
Okay, thanks a lot for answering.
