### ISSUE TITLE
Support encrypted communication between Karapace nodes

### ISSUE THREAD

**Issue by YuWang24** [aiven/karapace#265]
# What can we help you with?
Could anyone tell me wether Karapace supports internal TLS connection between one Karapace node to another Karapace node? I couldn't find such configs in the README. 

# Where would you expect to find this information?
This should be mentioned or clarified in the README.

**Comment by hackaugusto** [comment]
ATM for schema registry the communication is performed using just HTTP. Reference:

https://github.com/aiven/karapace/blob/3cd4769e2fafdfd9baf6c9dfec450d32ec08ab16/karapace/master_coordinator.py#L173

**Comment by hackaugusto** [comment]
I'm hijacking this issue. Renaming it from a question to a suggestion.

**Comment by hackaugusto** [comment]
@YuWang24 it would be nice to know why you were searching for this feature. Do you have nodes communicating over the public internet?

**Comment by tvainika** [comment]
> is this still an issue I have noticed self.sc.scheme = "http" is not longer in the source code. ?

Thank you for pointing out. This issue seems to have been fixed already some time ago in #511
