### ISSUE TITLE
Pre-built Docker image

### ISSUE THREAD

**Issue by FAntonescu** [aiven/karapace#269]
Is there a Docker image published to DockerHub or to a different public Docker registry?

**Comment by hackaugusto** [comment]
> Is there a Docker image published to DockerHub or to a different public Docker registry?

Yes, it is on [Docker Hub](https://hub.docker.com/r/aivenoy/karapace), this is the image:

https://github.com/aiven/karapace/blob/39f77135a8736a1e4c6dacdcfc2e67ba979d3181/container/docker-compose.yml#L59

**Comment by FAntonescu** [comment]
The DockerHub image does not have the same tags as the GitHub releases: https://github.com/aiven/karapace/releases 
Is it possible to create a Docker tag matching the 2.0.1 release?

**Comment by hackaugusto** [comment]
> The DockerHub image does not have the same tags as the GitHub releases: https://github.com/aiven/karapace/releases

Sorry about that, we will work on creating proper tagged releases: https://github.com/aiven/karapace/issues/245

>  Is it possible to create a Docker tag matching the 2.0.1 release?

I recommend using `latest`, the release `2.0.1` is a year old, and is missing features and bugfixes. Any reason why you would like to use that specific revision?

**Comment by FAntonescu** [comment]
Using the tag _latest_ is ok only during development, and not for production use - instead a specific version tag should be used. 

Imagine the following scenario: someone pulls the Docker image **karapace:latest** today 28.07.2021 and deploys it in a integration environment. After a few days/weeks several bugs are identified. Meanwhile, you release a couple more versions of the **latest** Docker tag. For which version should the developer report the bugs - latest?

It is a good practice to always use versioned releases, be it for libraries or for Docker images.

I noticed that **2.0.1** was the last tagged release mentioned in https://github.com/aiven/karapace/releases therefore I assumed it is the _latest_.

**Comment by hackaugusto** [comment]
> Using the tag latest is ok only during development, and not for production use - instead a specific version tag should be used.

If you want to rely on the tag to identify the version of the software, we are also pushing [the commit as a tag](https://hub.docker.com/r/aivenoy/karapace/tags?page=1&ordering=last_updated). This is not ideal, eventually we will also add the proper semantic version.

> Imagine the following scenario: someone pulls the Docker image karapace:latest today 28.07.2021 and deploys it in a integration environment. After a few days/weeks several bugs are identified. Meanwhile, you release a couple more versions of the latest Docker tag. For which version should the developer report the bugs - latest?

Yeah, reporting just `latest` would not be ideal. If this does happen, there are a few ways of getting the software version:

1- The images are using [opencontainer labels](https://github.com/opencontainers/image-spec/blob/main/annotations.md):
```sh
docker image inspect aivenoy/karapace:latest | jq '.[].ContainerConfig.Labels | {"org.opencontainers.image.version","org.opencontainers.image.revision"}'
{
  "org.opencontainers.image.version": "2.0.1-217-g863bf4a",
  "org.opencontainers.image.revision": "863bf4a7faec3b13eba57a0864e63f5e416cd6e3"
}
```
2- It is possible to run `--version` from the image/container:
```sh
docker run aivenoy/karapace:latest python3 -m karapace.karapace_all --version
2.0.1-217-g863bf4a
```

Hope that helps.
