### ISSUE TITLE
The constructor of AIOKafkaProducer in kafka_rest_apis/__init__.py cannot pass any SASL configurations. 

### ISSUE THREAD

**Issue by YuWang24** [aiven/karapace#299]
# What happened?

Support for SASL is missing in kafka_rest_apis/__init__.py `https://github.com/aiven/karapace/blob/881c09b7b831dac63dcdd1d207488d5024ae2c26/karapace/kafka_rest_apis/__init__.py#L180-L189`

The AIOKafkaProducer cannot pass any SASL configurations, which leads to failure of producing messages if Kafka has SASL configs. 

# What did you expect to happen?

The AIOKafkaProducer can pass the SASL configurations. 

Adding the following lines in between works:
```
sasl_mechanism=self.config["sasl_mechanism"],
sasl_plain_username=None if not self.config["sasl_plain_username"] else self.config["sasl_plain_username"],
sasl_plain_password=None if not self.config["sasl_plain_password"] else self.config["sasl_plain_password"],
```

# What else do we need to know?

None.

**Comment by tvainika** [comment]
This has been fixed by #426
