### ISSUE TITLE
tests/unit/test_protobuf_serialization.py::test_happy_flow is flaky

### ISSUE THREAD

**Issue by hackaugusto** [aiven/karapace#323]
Test failure: https://github.com/aiven/karapace/runs/5050128167?check_suite_focus=true
I couldn't reproduce it locally with:

```sh
while true; do pytest -n0 tests/unit/test_protobuf_serialization.py -k test_happy_flow; done
```

Needs further investigation.

[logs_3957.zip](https://github.com/aiven/karapace/files/7993878/logs_3957.zip)

**Comment by tvainika** [comment]
This test has been stable lately
