### ISSUE TITLE
Add support for advertised_port to Karapace Rest Proxy

### ISSUE THREAD

**Issue by YuWang24** [aiven/karapace#346]
# What is currently missing?

I am currently using a reverse proxy server (Nginx) in front of Karapace Rest Proxy. I am using the docker environment, and Nginx and Karapace are listening on different ports. When creating a consumer using Karapace:

```
curl -XPOST https://<domain>:<nginx-port>/consumers/consumer1 -u <username>:<password> \
--data '{"name": "my_consumer_instance", "format": "json", "auto.offset.reset": "earliest"}' \
--header "Content-Type: application/vnd.kafka.json.v2+json
```
The `base_uri` in response just gives me the karapace's port rather than the nginx port.
The response: 
`{"base_uri":"http://<ip>:<karapace-port>/consumers/consumer1/instances/my_consumer_instance","instance_id":"my_consumer_instance"}`

After checking the possible configs karapace has, it seems that there is not a config for `advertised_port`.

# How could this be improved?

Support of `advertised_port` could be added to the available configs to resolve such issues. When `advertised_port` is set, the response could display the `advertised_port` rather than `port`. By doing this, it can show the correct port in the consumer's response if Nginx is used along with Karapace. 

# Is this a feature you would work on yourself?

No

**Comment by hackaugusto** [comment]
@YuWang24 thank you for opening the issue. I will add this to our internal black log and tag this as `good first issue`.

**Comment by YuWang24** [comment]
Hey @hackaugusto, thanks for your reply. I am thinking doing it myself. I can add a boolean config `advertised_port` with default value of `None`. When it is set, this line [](https://github.com/aiven/karapace/blob/f6ac8f4b7c28be53eb7a6559ee258eb3b928eed4/karapace/kafka_rest_apis/consumer_manager.py#L32) will use `advertised_port` rather than `port`. 

Also, I found that the protocol in the `base_uri` response is using `http` as default, I am think of making this configurable if a secured proxy is used together with Karapace (for example my case). How about a config called `use_secured_proxy` or `behind_secured_proxy`? Default as `False`, when set `True`, this line [](https://github.com/aiven/karapace/blob/f6ac8f4b7c28be53eb7a6559ee258eb3b928eed4/karapace/kafka_rest_apis/consumer_manager.py#L32) will use `https` rather than `http`.

How do these sound?

**Comment by tvainika** [comment]
Fixing PR has been merged.
