### ISSUE TITLE
Delete subject config endpoint is missing

### ISSUE THREAD

**Issue by hackaugusto** [aiven/karapace#380]
# What happened?

```
curl -X DELETE 'http://localhost:8081/config/test' 
```

Return `405: Method Not Allowed`

# What did you expect to happen?

The endpoint should exist

**Comment by jjaakola-aiven** [comment]
This is done: https://github.com/aiven/karapace/commit/9e37fcad4ee35d64d1e5f2065832afaacbfe3764
