### ISSUE TITLE
Integration tests does not pass.

### ISSUE THREAD

**Issue by libretto** [aiven/karapace#394]
current revision of main branch show following messages.

pytest tests/integration
bringing up nodes...
.....................................................F........................................................ [ 72%]
..........................................                                                                     [100%]
====================================================== FAILURES ======================================================
______________________________________ test_schema_versions_deleting[pyloop-/] _______________________________________
[gw2] linux -- Python 3.7.11 /home/serge/anaconda3/envs/py3/bin/python
tests/integration/test_schema.py:988: in test_schema_versions_deleting
    await assert_schema_versions(registry_async_client, trail, schema_id_1, schema_1_versions)
        registry_async_client = <karapace.client.Client object at 0x7f9c7d96dd50>
        schema_1   = {'fields': [{'name': 'field_1', 'type': 'string'}, {'name': 'field_2', 'type': 'string'}], 'name': 'schema_test_schema_versions_deleting___1_19ee28a2', 'type': 'record'}
        schema_1_versions = [('subject_test_schema_versions_deleting___1_a4e52603', 1)]
        schema_2   = {'fields': [{'name': 'field_1', 'type': 'string'}], 'name': 'schema_test_schema_versions_deleting___1_19ee28a2', 'type': 'record'}
        schema_id_1 = 32
        schema_name = 'schema_test_schema_versions_deleting___1_19ee28a2'
        schema_str_1 = '{"type":"record","name":"schema_test_schema_versions_deleting___1_19ee28a2","fields":[{"name":"field_1","type":"string"},{"name":"field_2","type":"string"}]}'
        schema_str_2 = '{"type":"record","name":"schema_test_schema_versions_deleting___1_19ee28a2","fields":[{"name":"field_1","type":"string"}]}'
        subject    = 'subject_test_schema_versions_deleting___1_a4e52603'
        trail      = '/'
        version_1  = 1
tests/integration/test_schema.py:869: in assert_schema_versions
    assert len(res.json()) == len(expected)
E   AssertionError: assert 2 == 1
E    +  where 2 = len([{'subject': 'subject_test_record_nested_schema_compatibility-_1_1d67735c', 'version': 1}, {'subject': 'subject_test_schema_versions_deleting___1_a4e52603', 'version': 1}])
E    +    where [{'subject': 'subject_test_record_nested_schema_compatibility-_1_1d67735c', 'version': 1}, {'subject': 'subject_test_schema_versions_deleting___1_a4e52603', 'version': 1}] = <bound method Result.json of Result(status=200, json_result=[{'subject': 'subject_test_record_nested_schema_compatibility-_1_1d67735c', 'version': 1}, {'subject': 'subject_test_schema_versions_deleting___1_a4e52603', 'version': 1}])>()
E    +      where <bound method Result.json of Result(status=200, json_result=[{'subject': 'subject_test_record_nested_schema_compatibility-_1_1d67735c', 'version': 1}, {'subject': 'subject_test_schema_versions_deleting___1_a4e52603', 'version': 1}])> = Result(status=200, json_result=[{'subject': 'subject_test_record_nested_schema_compatibility-_1_1d67735c', 'version': 1}, {'subject': 'subject_test_schema_versions_deleting___1_a4e52603', 'version': 1}]).json
E    +  and   1 = len([('subject_test_schema_versions_deleting___1_a4e52603', 1)])
        client     = <karapace.client.Client object at 0x7f9c7d96dd50>
        expected   = [('subject_test_schema_versions_deleting___1_a4e52603', 1)]
        res        = Result(status=200, json_result=[{'subject': 'subject_test_record_nested_schema_compatibility-_1_1d67735c', 'version': 1}, {'subject': 'subject_test_schema_versions_deleting___1_a4e52603', 'version': 1}])
        schema_id  = 32
        trail      = '/'
------------------------------------------------- Captured log setup -------------------------------------------------
ERROR    kafka.consumer.fetcher:future.py:79 Fetch to node 1 failed: Cancelled: <BrokerConnection node_id=1 host=127.0.0.1:48730 <connected> [IPv4 ('127.0.0.1', 48730)]>
WARNING  KafkaSchemaReader:schema_reader.py:184 Topic: '_schemas' already exists
============================================== short test summary info ===============================================
FAILED tests/integration/test_schema.py::test_schema_versions_deleting[pyloop-/] - AssertionError: assert 2 == 1
1 failed, 151 passed in 205.46s (0:03:25)
(py3) serge@ax:/srv/archive/workspace/instaclustr/novage_office/karapace_mainstream$ pytest tests/integration
bringing up nodes...
.............................................................................................................. [ 72%]
..........................................                                                                     [100%]
152 passed in 203.45s (0:03:23)

**Comment by tvainika** [comment]
Yes, we noticed this some days ago. In our analysis it is flakiness due some parallel usage, and there is ongoing work to fix this in  #391.

As a workaround one can locally run tests with pytest-xdist argument `--numprocesses 1` to avoid parallelism, but also takes longer.

**Comment by hackaugusto** [comment]
#391 has been merged, the flakiness is vastly reduced.
