### ISSUE TITLE
How to start schema registry without docker?

### ISSUE THREAD

**Issue by kevinlam** [aiven/karapace#408]
# What can we help you with?

I am trying to use the schema registry to replace confluent's one, but I find it confusing on how to start the schema registry without using docker? there is lack of documentation on how to start using the python scripts?

# Where would you expect to find this information?

in the readme?

**Comment by jjaakola-aiven** [comment]
### First

```bash
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```

Both ways below assume activated virtualenv.

### Without installing with `setup.py`

```bash
python -m karapace.karapace_all <CONFIG_FILE>
```

### Install with `setup.py`

```bash
python setup.py install
karapace
```

**Comment by kevinlam** [comment]
Thanks for getting back to me. But when I ran the python setup.py install and then run karapace. I am getting this aiokafka not found?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jjaakola-aiven** [comment]
You had the virtualenv set and requirements installed, the `aiokafka` should get installed?

**Comment by kevinlam** [comment]
It's working now. Thank you sooooo much for your help. Understand that you guys prefer docker but my company isn't there yet :(

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
