### ISSUE TITLE
schema-registry avro primitive different than confluent

### ISSUE THREAD

**Issue by raphaelauv** [aiven/karapace#411]
# What happened?

The schema-registry of karapace do not manage the same way the primitive avro schema than the confluent schema-registry

# What did you expect to happen?

with `ghcr.io/aiven/karapace:3.1.2`

localhost:8081 is the port of the aiven schema-registry (karapace)

```shell
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
  --data '{"schema": "{\"type\": \"string\"}"}' \
  http://localhost:8081/subjects/test-key/versions
```

give {"id":1}

if I curl http://localhost:8081/schemas/ids/1 -> it give : `{"schema": "{\"type\": \"string\"}"}`

----

with `confluentinc/cp-schema-registry:7.1.0`

`localhost:8098` is the port of the confluent schema-registry

```shell
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schema": "{\"type\": \"string\"}"}' \
http://localhost:8098/subjects/test-key/versions
```
give `{"id":1}`

if I curl `http://localhost:8098/schemas/ids/1` -> it give : `{"schema":"\"string\""}`

**Comment by hackaugusto** [comment]
Hi @raphaelauv , thank you for the report. Does this causes issues though? Per the Avro spec `"string"` and `{"type": "string"}` are equivalent [1]:

    Primitive type names are also defined type names. Thus, for example, the schema "string" is equivalent to:

    {"type": "string"}

It could be that confluent performs canonicalization [2]:

     [PRIMITIVES] Convert primitive schemas to their simple form (e.g., int instead of {"type":"int"}).

1 - https://avro.apache.org/docs/current/spec.html#schema_primitive
2 - https://avro.apache.org/docs/current/spec.html#Transforming+into+Parsing+Canonical+Form

**Comment by raphaelauv** [comment]
Thanks for you response , it's now very clear.
