### ISSUE TITLE
Login unauthorized using non-admin users

### ISSUE THREAD

**Issue by AntoineDuComptoirDesPharmacies** [aiven/karapace#425]
# What happened?

I don't know if it is the best place to post issue with Karapace on Aiven.
Since this feature [406](https://github.com/aiven/karapace/pull/406) have been deployed to [Aiven for Apache Kafka®](https://aiven.io/kafka?utm_campaign=11903789758&utm_medium=cpc&utm_term=aiven%20kafka&utm_source=google&utm_matchtype=e&utm_target=kwd-752542950179&utm_content=487912510223&utm_adgroup=116008727712&gclid=EAIaIQobChMIwpCTx5_k-AIVoY1oCR29SQr6EAAYASAAEgIL4_D_BwE#top), it is not possible to login from Kafka Connectors to schema registry using account which is not admin.

# What did you expect to happen?

No regression, still being able to connect to schema registry with a classic service user.

# What else do we need to know?

Connector : Debezium - PostgreSQL
Version : 1.9.2.final

Yours faithfully,
LCDP

**Comment by tvainika** [comment]
I recommend you to contact Aiven's support as that way I'll get detailed help for configuring Karapace on Aiven environment. Also Aiven's support can immediately see your service details, and can investigate the configuration more if necessary.

The new authorization support in Karapace schema registry requires one to grant permissions for the operations for the user accounts as needed.  The old model where every service user account configured on Aiven platform having admin rights is being deprecated and has been removed in new Aiven services. The old services are kept running in the backward compatible configuration.

**Comment by thomas-chauvet** [comment]
Did you have any solution @AntoineDuComptoirDesPharmacies ?

Thanks!

**Comment by AntoineDuComptoirDesPharmacies** [comment]
Hi @thomas-chauvet,

Yes, we got some information from Aiven support, here it is : 
Since feature #406, all new Kafka service mounted on Aiven platform will enforce security on Karapaca through ACLs.
Existing Kafka service still run in compatibility mode that do not require these ACLs for the moment.

So, if you are creating a new Kafka service on Aiven, you now need to add ACLs to service users for them to read/write in Karapace. This can be done by command line or through terraform. **It can not be done through dashboard HMI yet.**
Command line : 
`avn service schema-registry-acl-add --project {your-project-name} --permission schema_registry_write --resource 'Subject:*' --username {your-service-username} {your-kafka-service-name}`

Terraform : 
```
# ACL for Kafka registry
resource "aiven_kafka_schema_registry_acl" "registry_acl" {
  resource     = "Subject:*"
  project      = {your-project-name}
  service_name = {your-kafka-service-name}
  username     = {your-service-username}
  permission   = "schema_registry_write"
}
```

Yours faithfully,
LCDP

**Comment by thomas-chauvet** [comment]
Super, thanks for your answer!
