### ISSUE TITLE
ACLs on subjects/<subject> endpoint

### ISSUE THREAD

**Issue by vitalvi** [aiven/karapace#431]
# What is currently missing?

Currently to call `subjects/<subject>` endpoint one must have Write permissions. Though this endpoint doesn't seem to change anything. It would be useful to have it available for users with Read permissions only in order to retrieve schema id.

# How could this be improved?

Basically it seems to be enough to set Read permission on `subjects_schema_post` method.

# Is this a feature you would work on yourself?
Perhaps

[x] I plan to open a pull request for this feature

**Comment by tvainika** [comment]
Fixing PR has been merged, and Karapace version 3.3.1 released containing the changes.
