### ISSUE TITLE
Bump to Avro 1.11.1

### ISSUE THREAD

**Issue by RyanSkraba** [aiven/karapace#439]
# What is currently missing?

Avro version 1.11.1 has been released with some python improvements: https://s.apache.org/avro-1.11.1-announce

# How could this be improved?

Python
- [AVRO-3542](https://issues.apache.org/jira/browse/AVRO-3542) Scale assignment optimization
- [AVRO-3521](https://issues.apache.org/jira/browse/AVRO-3521) "Scale" property from decimal object
- [AVRO-3380](https://issues.apache.org/jira/browse/AVRO-3380) Byte reading in avro.io does not assert read bytes to requested nbytes
- [AVRO-3229](https://issues.apache.org/jira/browse/AVRO-3229) validate the default value of an enum field
- [AVRO-3218](https://issues.apache.org/jira/browse/AVRO-3218) Pass LogicalType to BytesDecimalSchema

# Is this a feature you would work on yourself?

[X] I plan to open a pull request for this feature

**Comment by tvainika** [comment]
This was fixed in #516 where avro requirement was bumped to 1.11.1+ containing changed included in https://github.com/apache/avro/tree/branch-1.11 at the time of merge, and an approved patch from https://github.com/apache/avro/pull/2039
