### ISSUE TITLE
What's wrong with existing Kafka containers? Why use and manage your own? 

### ISSUE THREAD

**Issue by OneCricketeer** [aiven/karapace#52]
Please don't install and run an all-in-one container... 

Why re-invent the wheel? If you are going to re-write the Schema Registry from Confluent, why not just use their Docker images for your own purposes?

**Comment by encima** [comment]
Please use a more functional and informative topic. 

See [here](https://github.com/confluentinc/schema-registry/blob/master/LICENSE) that Schema Registry is not open source and see our post on the licensing changes [here](https://aiven.io/blog/aiven-statement-on-kafka-license/). We maintain and operate this with an open source license so the Kafka community can benefit; regardless of whether they are using the Aiven platform. 

If you have design suggestions and/or contributions, we would very much welcome them.

**Comment by OneCricketeer** [comment]
CCL defines it as source available. Aiven cannot host and profit from running Confluent's version, yes. 

However, that's not the point of this ticket. This ticket isn't explicitly about Confluent, it's the fact that you're not able to truly customize Zookeeper or the broker properties within the container via environment and that both Zookeeper and Kafka are not being treated as separate entities, as compared to using [Docker Compose for Kafka containers that are using open source Apache Kafka](https://github.com/bitnami/bitnami-docker-kafka/blob/master/docker-compose.yml) 

---
> We maintain and operate this with an open source license so the Kafka community can benefit; regardless of whether they are using the Aiven platform.

Works for me. I'll add it to the list 

- https://github.com/hortonworks/registry 
- https://developers.redhat.com/blog/2019/12/17/replacing-confluent-schema-registry-with-red-hat-integration-service-registry/

**Comment by vtainio** [comment]
Hi,

There is indeed a lot to improve on the container side of this project. The current container that we have is only designed for quickly running a similar environment as we have for our unit tests for local debugging. That means just running the same Kafka version and Zookeeper quickly in Fedora (which is the main development OS that we use). It's actually not even used by the CI system that we have and is definitely not intended for any kind of production use. Do note that Karapace itself only requires connection parameters for Kafka so if you want to run the Confluent Docker images locally and connect Karapace to them, it's very easy to do. We will definitely improve the containers in this project and add documentation for them and for the use cases. Additionally, the Karapace project itself will be containerized properly in the future.

Hopefully this gives a bit of background into why the container file is such a barebones implementation at the moment.

**Comment by OneCricketeer** [comment]
Thanks for the response.

One question: why can't your tests use Docker Compose or any existing Kafka container?

**Comment by gabriel-tincu** [comment]
> Thanks for the response.
> 
> One question: why can't your tests use Docker Compose or any existing Kafka container?

As the tests are built at the moment, each test run will actually spawn a ZK instance and a Kafka instance per test run. This mostly keeps things clean in case someone decides to use a non randomly generated topic name for example. It also takes away from the hassle of checking if your cluster is running properly when all you want is to implement a quick fix or minor feature and shorter dev cycles are always a good thing IMO. Of course, if you end up running said unit tests 100 times in a row then having a pre existing cluster running would make more sense.

Having said tests run on top of an existing pre running kafka cluster could be achieved in a relatively painless manner by updating the `fixture_kafka_server` and `fixture_zkserver` code to for example check some environment variable and return a normal config file without actually going through the steps of spawning said instances. 
Hope that clears things up a bit

**Comment by OneCricketeer** [comment]
> each test run will actually spawn a ZK instance and a Kafka instance per test run

Sure... `docker-compose` can be used for that rather than starting both processes in one container was my point

**Comment by gabriel-tincu** [comment]
> > each test run will actually spawn a ZK instance and a Kafka instance per test run
> 
> Sure... `docker-compose` can be used for that rather than starting both processes in one container was my point. Note: I said _container_, not cluster

In this context i think its safe to use the terms interchangeably, as in, a kafka service that is not "managed" by the unit test fixtures. Also, one aspect that slipped my mind in my previous reply:
- We're running the unit tests as a github check , so having a fixture managed instance is kind of a must

**Comment by OneCricketeer** [comment]
> fixture managed instance

Docker compose is (currently) a Python based project. You can could also manage the instances using a few shell commands and `os.exec`, so you I'm not sure I understand your point

**Comment by gabriel-tincu** [comment]
> > fixture managed instance
> 
> Docker Compose is (currently) a Python based project. You can could also manage the instances using a few shell commands and `os.exec`, so I'm not sure I understand your point

My point was that i was not sure weather github workflows allow access to docker, but apparently they do. So i guess i can change my answer to : we can use docker containers for the test suite. Weather we should or not is probably an issue for another ticket

**Comment by galvo** [comment]
Understanding the reasons why it was not possible to use Confluent Schema Registry if you going to write you own schema registry a minimum requirement should really be to make versioned docker images available for it on Docker Hub. 

At the moment id imagine this is a big gap for most organisation looking to integrate with Aiven as Karapsace would be something they would like to test against early in their CI pipelines and currently they have would have to build Karaspace themselves, which also is a challenge based on existing documentation and Dockerfile see https://github.com/aiven/karapace/issues/86

**Comment by hackaugusto** [comment]
Closing the issue:
- The docker images are available at https://hub.docker.com/r/aivenoy/karapace/
- We don't have an all-in-one image anymore. [Here is an example docker-compose file](https://github.com/aiven/karapace/blob/master/container/docker-compose.yml)

**Comment by galvo** [comment]
Any chance ye can start versioning these images? There doesn't seem to be a release strategy on Karapace that we can correlate with the version that is running on Aiven Cloud, it just seems that everything is latest. In the past i have found what was latest on Githib wasn't even compilable. We need to be able to align the versions we run in docker with what is deployed to our clusters on Aiven cloud.

**Comment by hackaugusto** [comment]
Hi @galvo,

> Any chance ye can start versioning these images?

Yes, the plan is to start doing releases with semver.

> There doesn't seem to be a release strategy on Karapace that we can correlate with the version that is running on Aiven Cloud, it just seems that everything is latest

`latest` matches the version for *new services* or services for which maintenance update has been performed recently.

Please note that `latest` may not be the same version of an existing service, if it has pending updates. If you keep your services up-to-date, using `latest` will match production. Please let me know if you need to support no-so-up-to-date services, in that case we would need to add the Karapace version to our service's API.
