### ISSUE TITLE
Deprecated module cgi

### ISSUE THREAD

**Issue by aiven-anton** [aiven/karapace#533]
# What happened?

Reported by pylint:

```
karapace/rapu.py:21:0: W4901: Deprecated module 'cgi' (deprecated-module)
```

# What did you expect to happen?

# What else do we need to know?

We should replace this dependency.

**Comment by jjaakola-aiven** [comment]
FastAPI has been considered, https://github.com/aiven/karapace/issues/470

**Comment by aiven-anton** [comment]
@jjaakola-aiven That makes sense, we can probably close this one if we're committed to that path. I just wanted to have placeholder for the ignored import. It'll be removed in 3.13, so we have some time.
