### ISSUE TITLE
Creating a schema from `provectus/kafka-ui` results in a `TypeError: 'NoneType' object is not iterable`

### ISSUE THREAD

**Issue by Eijebong** [aiven/karapace#591]
# What happened?

When creating a schema from the `provectus/kafka-ui` project, it sends a post like that:

`POST with subject: 'aa', request: {'schema': '{}', 'schemaType': 'JSON', 'references': None}`

Note the `references` set to None. This results in this traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/karapace/rapu.py", line 326, in _handle_request
    data = await callback(**callback_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/karapace/schema_registry_apis.py", line 1143, in subject_post
    references = self._validate_references(content_type, schema_type, body)
  File "/usr/local/lib/python3.9/dist-packages/karapace/schema_registry_apis.py", line 1010, in _validate_references
    for reference in references:
TypeError: 'NoneType' object is not iterable
```

# What did you expect to happen?

This should not traceback. If None is an invalid value here then it should at least return a message saying so and an issue should be opened on the kafka-ui project.

# What else do we need to know?

The support for this key was added by 7e1de2a75bfba2f7ef2087a37907e25f21dc5e28. I'm running the latest `develop` image at the time of writing this (`sha256:2cf7d6202aea913d696f25b20705d84672d55b6bd461d83385f05791c1245fbe`).

**Comment by aiven-anton** [comment]
Thank you for reporting this issue @Eijebong, a fix has now been merged in #599.
