### ISSUE TITLE
add support for jsonschema

### ISSUE THREAD

**Issue by gabriel-tincu** [aiven/karapace#62]
[ ] differentiate between the 2 schema types
[ ] some basic validation rules to get started with
[ ] support for schema references
[ ] support for proper same type promotion based on restrictions

**Comment by Samlinxia** [comment]
Hi @gabriel-tincu , do you have rough estimated timeline to support JSON schema? Thanks!

**Comment by hackaugusto** [comment]
Hello @Samlinxia , sorry for the late response. The support has been introduced by https://github.com/aiven/karapace/pull/171 and https://github.com/aiven/karapace/pull/192.

**Comment by Samlinxia** [comment]
@hackaugusto , thank you for the update
