### ISSUE TITLE
it is possible to  produce an event with a different schema than the one attached to the topic 

### ISSUE THREAD

**Issue by haassm** [aiven/karapace#658]
You attach schema to the topic named EXAMPLE_TOPIC 
You take the schema_id, put it into your event, put payload that follows to schema into the event - that is correct 
You go to different topic named DIFFERENT_TOPIC with different incompatible schema - you steal its different schema id
You construct event with stolen schema_id a with payload that follows the stolen schema
You are still able to produce this event to the EXAMPLE_TOPIC, even though you follow the DIFFERENT_TOPIC schema, which is incompatible

# What did you expect to happen?
error message stating the schema_id is not attached to this topic

**Comment by jjaakola-aiven** [comment]
@haassm Could you provide an example code how to reproduce this?

**Comment by haassm** [comment]
```
curl -X POST https://broker-1-dbb-intplat-sbx.aivencloud.com:22160/topics/SANDBOX-PLATFORM_TEST \
-u "user_name:password" \
-H "Content-Type: application/vnd.kafka.avro.v2+json" \
-H "Accept: application/vnd.kafka.avro.v2+json" \
-d "{
\"value_schema_id\": 7,
\"records\": [
   {\"key\" : null ,
     \"value\": {
    \"id\": \"C234-1234-1234\",
    \"source\": \"/mycontext\",
    \"specversion\": \"1.0\",
    \"type\": \"com.example.someevent\",
    \"schemaid\": \"1\",
    \"createdat\": 1676537963000,
    \"data\": {
          \"uuid_payload\": \"4a58118e-6e28-4993-8ba0-da13e60449a4\",
          \"random_payload\": \"iofdksjglkdg\"
          }
      }
   }
]
}"

curl -X POST https://broker-1-dbb-intplat-sbx.aivencloud.com:22160/topics/SANDBOX-PLATFORM_TEST \
-u "user_name:password" \
-H "Content-Type: application/vnd.kafka.avro.v2+json" \
-H "Accept: application/vnd.kafka.avro.v2+json" \
-d "{
\"value_schema_id\": 5,
\"records\": [
   {\"key\" : null ,
     \"value\": {
    \"id\": \"C234-1234-1234\",
    \"source\": \"/mycontext\",
    \"specversion\": \"1.0\",
    \"type\": \"com.example.someevent\",
    \"schemaid\": \"1\",
    \"createdat\": 1676537963000,
    \"data\": {
          \"produce_time_timestamp\": 1686732557,
          \"string_payload\": \"iofdksjglkdg\"
          }
      }
   }
]
}"
```

Grüße
Martin Haaß

--------
Martin Haaß
Architect
C-TIHF

EnBW Energie Baden-Wuerttemberg AG
Durlacher Allee 93 · 76131 Karlsruhe · Germany
Registered office: Karlsruhe
Court of Registry: Mannheim · Register No: HRB 107956
Chairman of the Supervisory Board: Lutz Feldmann
Executive Committee: Andreas Schell (Chairman), Dirk Güsewell, Thomas Kusterer, Colette Rückert-Hennen, Dr. Georg Stamatelopoulos
