### ISSUE TITLE
Registry container is failing on startup via docker-compose

### ISSUE THREAD

**Issue by bnodya** [aiven/karapace#82]
I am trying to start karapace via docker-compose file. I built image and when docker-compose is launching components, then I am getting following error:

```
registry_1  | Traceback (most recent call last):
registry_1  |   File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
registry_1  |     "__main__", mod_spec)
registry_1  |   File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
registry_1  |     exec(code, run_globals)
registry_1  |   File "/app/karapace/schema_registry_apis.py", line 1, in <module>
registry_1  |     from karapace import version as karapace_version
registry_1  | ImportError: cannot import name 'version' from 'karapace' (/app/karapace/__init__.py)
```
Then container_registry_1 exits with code 0

Kafka and Zookeeper starts and operates successfully.

What could be causing this issue?

**Comment by gabriel-tincu** [comment]
Handled here https://github.com/aiven/karapace/pull/84

**Comment by vtainio** [comment]
Closing the issue as this should now be fixed. Thank you @bnodya  for reporting it!

**Comment by bnodya** [comment]
Thank you all for quick response!
