### ISSUE TITLE
Provide instructions for container usage

### ISSUE THREAD

**Issue by hguerrero** [aiven/karapace#88]
There is missing documentation on how to use the container images for deployment of the registry and rest proxy. 

Information missing: 
- How to access the container image (name, repository, etc)
- How to configure the registry and proxy
- How to connect to external Kafka

**Comment by arkanmgerges** [comment]
@hguerrero Good point. In my case, I need helm installation in order to install it in my private cloud.

**Comment by hackaugusto** [comment]
Hi @hguerrero , we are now publishing images to hub.docker.com and updated the [README](https://github.com/aiven/karapace#using-docker), with some instructions on how to run using `docker-compose`. Do you think these changes are sufficient?

**Comment by hackaugusto** [comment]
We are publishing images to the github registry now :)
