### ISSUE TITLE
Schema not found (40403) for existing schema using POST /subjects/<subject>

### ISSUE THREAD

**Issue by pederpansen** [aiven/karapace#89]
Hi,

we are in the process of migrating a Kafka Streams application to another cluster. In this process, we have copied the '_schemas' from our old (Confluent) schema registry to the new Aiven/Karapace one. However, the app throws the following error:

```
org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema: {\"type\":\"record\",\"name\":\"MyKey\",\"namespace\":\"my.example.key\",\"fields\":[{\"name\":\"did\",\"type\":\"string\"},{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"}]}
```

Upon further debuuging, I found the reason is when the schema refistry client is trying to look up the schema id by the schema string using POST /subjects/<subject> with the following body:

```
{"schema":"{\"type\":\"record\",\"name\":\"MyKey\",\"namespace\":\"my.example.key\",\"fields\":[{\"name\":\"did\",\"type\":\"string\"},{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"}]}"}
```

This fails with an error code of 40403, as I can reproduce using `curl`.

However, the subject clearly exists with the exact same schema string in the registry:

```
GET /subjects/<mytopic>-key/versions/latest | jq '.schema'
{"id":1155,"schema":"{\"type\":\"record\",\"name\":\"MyKey\",\"namespace\":\"my.example.key\",\"fields\":[{\"name\":\"did\",\"type\":\"string\"},{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"}]}","subject":"<mytopic>-key","version":1}
```

What is going on here, does the POST-endpoint not work as expected?

**Comment by pederpansen** [comment]
There seems to be a workaround for the above error by setting `auto.register.schemas` to `true` in the Serde configs.

**Comment by gabriel-tincu** [comment]
Hello and sorry for the late reply. It would be helpful if you provided both a dump of the `_schemas` topic, or at least a list of the ones relevant to your subject, plus the actual requests being made plus the returned codes

**Comment by pederpansen** [comment]
Hi. 

This is an example schema taken from the `_schemas` topic (some internal naming has been changed) - there exists only a single version in the topic:

```
{
  "subject": "mytopic-key",
  "version": 1,
  "id": 1155,
  "schema": "{\"type\":\"record\",\"name\":\"MyKey\",\"namespace\":\"my.namespace.key\",\"fields\":[{\"name\":\"did\",\"type\":\"string\"},{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"}]}",
  "deleted": false
}
```

And this is the corresponding POST request (basic auth credentials omitted):

```
curl -X POST \
  https://<aiven-kafka-endpoint>/subjects/mytopic-key \
  -H 'content-type: application/json' \
  -d '{"schema":"{\"type\":\"record\",\"name\":\"MyKey\",\"namespace\":\"my.namespace.key\",\"fields\":[{\"name\":\"did\",\"type\":\"string\"},{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"}]}"}'
```
 which returns `{"error_code":40403,"message":"Schema not found"}`.

**Comment by nick-zh** [comment]
This might not apply here, but i had some issues as well a while back with similar calls. While `application/json` is accepted, in my case i was able to resolve my issue by using `application/vnd.schemaregistry.v1+json` which is the preferred type [as per doc](https://docs.confluent.io/current/schema-registry/develop/api.html#content-types).

**Comment by gabriel-tincu** [comment]
> {"schema":"{\"type\":\"record\",\"name\":\"MyKey\",\"namespace\":\"my.namespace.key\",\"fields\":[{\"name\":\"did\",\"type\":\"string\"},{\"name\":\"company\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"}]}"}

I seem to have problems reproducing the issue on a local karapace instance. The 2 strings you are using look identical. Can you please tell us if you are using the latest karapace version?
Thank you

**Comment by pederpansen** [comment]
I mentioned the issue in an Aiven.io support request, I was told to upgrade to the newest Karapace version and indeed, the issue does not persist in the latest version - closing.
