### ISSUE TITLE
Compatibility check for union types doesn't work

### ISSUE THREAD

**Issue by nick-zh** [aiven/karapace#98]
Having a schema like this in the registry
```
{
  "type": "record",
  "name": "order",
  "namespace": "example",
  "fields": [
    {
      "name": "someField",
      "type": [
        "null",
        {
          "type": "record",
          "name": "someEmbeddedRecord",
          "namespace": "example",
          "fields": [
            {
              "name": "name",
              "type": "string"
            }
          ]
        }
      ],
      "default": null
    }
  ]
}
```
and trying to update to this
```
{
  "type": "record",
  "name": "order",
  "namespace": "example",
  "fields": [
    {
      "name": "someField",
      "type": [
        "null",
        {
          "type": "record",
          "name": "someEmbeddedRecord",
          "namespace": "example",
          "fields": [
            {
              "name": "name",
              "type": "string"
            },
            {
              "name": "price",
              "type": "int"
            }
          ]
        }
      ],
      "default": null
    }
  ]
}
```
Karapace rest call for compatibility claims, that it is compatible.
For `full_transitive` only this version should be allowed:
```
            {
              "name": "price",
              "type": [
                "null",
                "int"
              ],
              "default": null
            }
```

Curl call to register the schema:
```
curl --location --request POST 'localhost:9081/subjects/test/versions' \
--header 'Accept: application/vnd.schemaregistry.v1+json' \
--header 'Content-Type: application/vnd.schemaregistry.v1+json' \
--data-raw '{"schema":"{\"type\":\"record\",\"name\":\"order\",\"namespace\":\"example\",\"fields\":[{\"name\":\"someField\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"someEmbeddedRecord\",\"namespace\":\"example\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"}]}],\"default\":null}]}"}'
```
Curl call to check compatibility:
```
curl --location --request POST 'localhost:9081/compatibility/subjects/test/versions/latest' \
--header 'Accept: application/vnd.schemaregistry.v1+json' \
--header 'Content-Type: application/json' \
--data-raw '{"schema":"{\"type\":\"record\",\"name\":\"order\",\"namespace\":\"example\",\"fields\":[{\"name\":\"someField\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"someEmbeddedRecord\",\"namespace\":\"example\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"int\"}]}],\"default\":null}]}"}'
```
Karapace claims:
```
{
    "is_compatible": true
}
```

**Comment by gabriel-tincu** [comment]
@nick-zh I'm trying to reproduce the results with the master branch, but am unable to do so, by neither just pushing a new schema as in the unit test, or hitting the compat check endpoint, as in your code sample (that one returns false). Can you please let me know what version karapace you are running?
Take note that all i am doing is run the 2 curl commands against a fresh karapace instance, runing against a fresh kafka cluster.
Thank you

**Comment by nick-zh** [comment]
@gabriel-tincu i am using a hosted version, not sure how i can check. But i saw we have an open maintenance update mentioning improving compatibility checks. I am applying it to see if that fixes it :v:

**Comment by nick-zh** [comment]
@gabriel-tincu ok so after applying the maintenance update this still persists, i am not sure how i can check the version that i am using in the cloud though. Also since i am using the test system, i tried to register this schema (that breaks compatibility), which is possible, despite having set the global compatibility set to `FULL_TRANSITIVE`. Unless i am missing something, i think this is actually quite the dangerous bug.

**Comment by gabriel-tincu** [comment]
understood.... i will continue investigating

**Comment by nick-zh** [comment]
@gabriel-tincu thanks a lot! Let me know if i can assist any further. In my GH profile you can see my company as well, if you need to contact me by email :v:

**Comment by nick-zh** [comment]
As discussed, doesn't affect Karapace but the other SR, sry for the confusion, closing.
